name: expected_response
description: Treat the http responses in a idiomatic manner
version: 1.0.0
author: Eduardo Sabino da Silva Aikin <eduardoaikin@gmail.com>
homepage: https://github.com/EdSabino/http_response

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.0.0