name: expected_response_generator
description: Handles the generator of the expected_response package, must be used aside with it.
version: 1.0.0+1
author: Eduardo Sabino da Silva Aikin <eduardoaikin@gmail.com>
homepage: https://github.com/EdSabino/http_response

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.38.2
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  expected_response: ^1.0.0
  
dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^1.0.0
  test: ^1.0.0